development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: fliplingo_development
  pool: 500
  username: postgres
  password:
  min_messages: warning

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: fliplingo_test
  pool: 500
  username: postgres
  password:
  min_messages: warning

production:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: fliplingo_test
  pool: 500
  username: postgres
  password:
  min_messages: warning